### ISSUE TITLE
【已部分解决】有关MacOS下的打包

### ISSUE THREAD

**Issue by Happievening** [FHChen0420/LyricDanmu#3]
## 配置等信息
```ini
MacBook Pro 2015(i7-4770HQ, macOS Mojave 10.14.3)
MacBook Air 2020(M1, macOS Monterey 12.3.1)
```
LyricDanmu的源码为1.4.4b版本

## 1.【已解决】 pyinstaller打包时报路径错误
上述两台mac电脑上按照教程的指令分别尝试了打包，pyinstaller报错：
```txt
pyinstaller: error: argument --add-data: invalid add_data_or_binary value: './chaser/static/flv.js'
```
经尝试后，发现在路径上加入引号变为字符串可以解决：
```shell
pyinstaller -F -w MainFrame.pyw -n LyricDanmu --add-data "./chaser/static/*:./chaser/static" 
```

## 2. M1芯片的mac缺乏相应的库
intel的Mac在打包后功能正常，但是M1芯片还缺乏一些库（看报错信息，有zlib）无法打原生的包，现在暂时用rosetta运行x86版的程序顶着，功能上目前没发现问题。个人之后或许会尝试一下编译arm版的zlib库（懒）。

**Comment by FHChen0420** [comment]
感谢指正，mac系统我其实还不是很熟悉，之后会对readme文件进行修改。

**Comment by Happievening** [comment]
源码更新至1.5.3版本之后 在打包时做一些小的调整 似乎已经可以打原生的包了。
当前的运行环境是 macOS Monterey12.6 + python 3.9.6
我个人的方案是这样（不一定通用）

1. requirements里的wxPython版本改为最新的4.2.0（维持4.1.1的话 我这里之后安装会报错）
2. 然后手动安装UPX:
```
brew install --build-from-source upx
```
3. 然后运行原来的打包命令
```
pyinstaller -F -w app.pyw -n LyricDanmu --add-data "./static/*:./static"
```
打开dist下的LyricDanmu.app即可使用（有个现象 Dock栏图标会闪退 但是过几秒仍然可以正常打开）
<img width="682" alt="image" src="https://user-images.githubusercontent.com/77200138/191827058-f45d7ab5-2dfd-4e87-8ff5-f35926e35d77.png">

目前测试了扫码登录、基本的发送弹幕，尚未发现问题。
