### ISSUE TITLE
追帧失败

### ISSUE THREAD

**Issue by Kotagan** [FHChen0420/LyricDanmu#4]
![image](https://user-images.githubusercontent.com/25102488/168470479-25c452e5-189f-475e-961f-04db828546d9.png)
追帧失败，原因不明

**Comment by FHChen0420** [comment]
403报错猜测是海外IP的缘故？在其他开播的直播间也是这样吗？
歌词机的追帧功能是半年之前一位大佬帮我加的，相较于其他追帧工具，其限制条件还是比较多的，比方说可能不支持HEVC直播流（错误码475），以后会考虑改进一下的
追帧的话可以试试“同传姬”这个网站：
上线地址 https://danmu.sea-group.org/
项目地址 https://github.com/diannaojiang/Transle_Danmu

**Comment by Kotagan** [comment]
> 403报错猜测是海外IP的缘故？在其他开播的直播间也是这样吗？ 歌词机的追帧功能是半年之前一位大佬帮我加的，相较于其他追帧工具，其限制条件还是比较多的，比方说可能不支持HEVC直播流（错误码475），以后会考虑改进一下的 追帧的话可以试试“同传姬”这个网站： 上线地址 https://danmu.sea-group.org/ 项目地址 https://github.com/diannaojiang/Transle_Danmu

其实之前是可以的，感觉不像海外ip的问题？这几天突然不行了，不太清楚是什么原因。总之先谢谢啦

**Comment by FHChen0420** [comment]
新版本v1.5.1已发布，更换了播放组件，可以测一下能否正常使用追帧功能

**Comment by Kotagan** [comment]
好像正常了，3q
