### ISSUE TITLE
弹幕转发添加延迟设定

### ISSUE THREAD

**Issue by gin3715** [FHChen0420/LyricDanmu#5]
目前的弹幕转发行为是收到弹幕以后立刻加入发送队列。
请问是否可以考虑添加转发延迟？对于同传较快的房间，可以设置为等待一定的毫秒数再进行转发，从而实现不同房间的同传能在转发后相对同步。

**Comment by FHChen0420** [comment]
1.5.3版本已更新，在转发界面点击齿轮按钮可以设置转发延迟
