### ISSUE TITLE
如何更改热键绑定

### ISSUE THREAD

**Issue by Yellabble** [FHChen0420/LyricDanmu#7]
软件的热键冲突了 想更改热键

**Comment by FHChen0420** [comment]
这个我可以加一个简单的配置。想问一下具体是哪个热键冲突了？
另外，目前主要是用alt加其他键作为热键，想问一下是否需要有ctrl或shift这样的键位需求？

**Comment by FHChen0420** [comment]
已更新1.5.3a，试试看能不能用（默认把alt+P禁用了，毕竟这个只是我自己测试屏蔽词用的）

**Comment by Yellabble** [comment]
能用了！谢谢更新！
